### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by ahoka** [kwent/pgbouncerhero#3]
Hi guys,

Nice project! How about a Dockerfile for easy deployment? :-)

Cheers,
Adam

**Comment by kwent** [comment]
@ahoka Definitely ! I'll going to be busy in the next few weeks but it's in my plan ! Open to PR as well.

**Comment by kwent** [comment]
Hi @ahoka. 

Here is a Dockerfile example: https://github.com/kwent/pgbouncerhero-demo/blob/master/Dockerfile

Regards

**Comment by encryptblockr** [comment]
Dockerfile build is failing

https://github.com/kwent/pgbouncerhero-demo/issues/8
