### ISSUE TITLE
Namespace overlap with ApplicationController

### ISSUE THREAD

**Issue by wasifhossain** [kwent/pgbouncerhero#6]
We are trying to use this engine in our ActiveAdmin application. We followed the configuration steps as described and mounted the engine as:
```
mount PgBouncerHero::Engine, at: 'pgbouncerhero'
```

But when we visit the app at `/pgbouncerhero`, it fails and the server log indicates that its trying to run code defined in our ActiveAdmin controller `ApplicationController`, instead of `PgBouncerHero::ApplicationController`.

So we put this line 
```
require_relative 'application_controller'
```
at the top of `app/controllers/pg_bouncer_hero/home_controller.rb` and `app/controllers/pg_bouncer_hero/database_controller.rb`, and **with this change, everything works as expected**!

Do you have any better idea how to resolve such case? Eager to know how to fix it.

Thanks.

**Comment by kwent** [comment]
Hi @wasifhossain,

Just released `1.0.1`(https://github.com/kwent/pgbouncerhero/releases/tag/1.0.1) which should fix this.
