### ISSUE TITLE
Allow to add pgbouncerhero without css/js files

### ISSUE THREAD

**Issue by MaicolBen** [kwent/pgbouncerhero#9]
Awesome tool! I have an API and I don't want to be adding css/js files, like [pghero](https://github.com/ankane/pghero) you can compile the assets in the lib so we don't depend on compiling the assets in the main app. Thanks!

**Comment by kwent** [comment]
@MaicolBen Not sure i understand. Could you detail more ?

**Comment by MaicolBen** [comment]
I don't want to do this (because it's just plain API):
<img width="425" alt="Screen Shot 2020-04-10 at 15 19 50" src="https://user-images.githubusercontent.com/3474627/79013421-12fdcb00-7b3f-11ea-9079-31a35b4d223e.png">
Check https://github.com/ankane/pghero/blob/master/app/views/layouts/pg_hero/application.html.erb#L8, it isn't a bug it's just a nice thing to have out of the box

**Comment by MichaelDBA** [comment]
wow, talk about an issue with long pauses between communication!

**Comment by kwent** [comment]
@MaicolBen @MichaelDBA, sorry for the delay latest update is fixing this issue https://rubygems.org/gems/pgbouncerhero/versions/2.0.0.
